
import pandas as pd
import streamlit as st

from modules.ai_schedule_builder import (
    get_ai_schedule_suggestions
)


# ==========================================================
# CONSTANTS
# ==========================================================

STATUS_OPTIONS = [
    "⏳ Pending",
    "✅ Approved",
    "✏️ Modified",
    "📌 Existing"
]

RELATIONSHIP_OPTIONS = [
    "No Predecessor",
    "Finish-to-Start (FS)",
    "Start-to-Start (SS)",
    "Finish-to-Finish (FF)",
    "Start-to-Finish (SF)"
]


# ==========================================================
# STATUS PROCESSING
# ==========================================================

def process_ai_editor_change():
    widget_key = (
        "ai_relationship_editor_widget_"
        + str(st.session_state.get("ai_editor_version", 0))
    )

    # ------------------------------------------------------
    # Get the change information generated by st.data_editor
    # ------------------------------------------------------
    editor_state = st.session_state.get(widget_key)

    if not isinstance(editor_state, dict):
        return

    # ------------------------------------------------------
    # Get current AI table
    # ------------------------------------------------------
    edited = st.session_state.get("ai_editor_data")

    if edited is None:
        return

    if not isinstance(edited, pd.DataFrame):
        return

    edited = edited.copy()

    # ------------------------------------------------------
    # Get original AI suggestions
    # ------------------------------------------------------
    original = st.session_state.get("ai_original_suggestions")

    if original is None:
        return

    if not isinstance(original, pd.DataFrame):
        return

    original = original.copy()

    # ------------------------------------------------------
    # Apply only cells changed by the user
    # ------------------------------------------------------
    edited_rows = editor_state.get("edited_rows", {})

    changed_rows = set()

    for row_index, changes in edited_rows.items():

        try:
            row_index = int(row_index)
        except Exception:
            continue

        if row_index < 0 or row_index >= len(edited):
            continue

        if not isinstance(changes, dict):
            continue

        changed_rows.add(row_index)

        for column, value in changes.items():

            if column in edited.columns:
                edited.at[row_index, column] = value

    # ------------------------------------------------------
    # Update status ONLY for rows changed in this edit
    # ------------------------------------------------------
    for index in changed_rows:

        if index >= len(original):
            continue

        original_predecessor = str(
            original.loc[index, "Suggested Predecessor"]
        ).strip()

        original_relationship = str(
            original.loc[index, "Relationship"]
        ).strip()

        current_predecessor = str(
            edited.loc[index, "Suggested Predecessor"]
        ).strip()

        current_relationship = str(
            edited.loc[index, "Relationship"]
        ).strip()

        original_status = str(
            original.loc[index, "Status"]
        ).strip()

        # --------------------------------------------------
        # Existing manually defined relationship
        # --------------------------------------------------
        if original_status == "📌 Existing":

            edited.loc[index, "Status"] = "📌 Existing"

            continue

        # --------------------------------------------------
        # Relationship/predecessor changed
        # --------------------------------------------------
        if (
            current_predecessor != original_predecessor
            or current_relationship != original_relationship
        ):

            edited.loc[index, "Status"] = "✏️ Modified"

            if "Approve" in edited.columns:
                edited.loc[index, "Approve"] = False

        # --------------------------------------------------
        # Approval checkbox changed
        # --------------------------------------------------
        elif (
            "Approve" in edited.columns
            and bool(edited.loc[index, "Approve"])
        ):

            edited.loc[index, "Status"] = "✅ Approved"

        else:

            edited.loc[index, "Status"] = "⏳ Pending"

    # ------------------------------------------------------
    # Save updated data
    # ------------------------------------------------------

    st.session_state.ai_editor_data = edited.copy()

    # ------------------------------------------------------
    # Any new edit invalidates the previous saved review
    # ------------------------------------------------------

    if changed_rows:

        st.session_state.ai_relationship_saved = False

        st.session_state.ai_validation_passed = False

        st.session_state.pop(
            "ai_saved_relationships",
            None
        )

        st.session_state.pop(
            "ai_saved_review",
            None
        )

        # Any relationship edit makes the existing
        # proposed schedule stale.

        st.session_state.pop(
            "proposed_schedule",
            None
        )

        st.session_state.pop(
            "schedule_warnings",
            None
        )

    # ------------------------------------------------------
    # IMPORTANT:
    # DO NOT increment ai_editor_version here.
    # ------------------------------------------------------
    # Incrementing it destroys and recreates the data editor,
    # which causes:
    # - table refresh
    # - scroll reset
    # - fullscreen exit
    # - table resizing
    # ------------------------------------------------------

# ==========================================================
# APPLY SAVED AI RELATIONSHIPS TO ACTIVITY DATA
# ==========================================================


# ==========================================================
# APPLY SAVED AI RELATIONSHIPS TO A COPY
# ==========================================================

def convert_ai_relationships_to_activity_data(
    activities,
    reviewed_data
):
    """
    Convert the user-facing activity names in the AI table
    into internal Activity IDs.

    This function does NOT modify session_state.activities.
    It returns a new DataFrame.

    The actual Activity Register is intentionally left
    unchanged until the scheduling workflow decides to
    apply the reviewed relationships.
    """

    updated = activities.copy()

    name_to_ids = {}

    for _, row in activities.iterrows():

        activity_id = str(
            row["ID"]
        ).strip()

        activity_name = str(
            row["Activity"]
        ).strip()

        if activity_name not in name_to_ids:

            name_to_ids[activity_name] = []

        name_to_ids[activity_name].append(
            activity_id
        )

    errors = []

    for index in reviewed_data.index:

        row = reviewed_data.loc[index]

        predecessor_name = str(
            row["Suggested Predecessor"]
        ).strip()

        relationship = str(
            row["Relationship"]
        ).strip()

        # ----------------------------------------------
        # No predecessor
        # ----------------------------------------------

        if (
            not predecessor_name
            or predecessor_name == "None 🔍"
        ):

            updated.at[
                index,
                "Predecessor"
            ] = ""

            updated.at[
                index,
                "Relationship"
            ] = "No Predecessor"

            continue

        # ----------------------------------------------
        # Find internal Activity ID
        # ----------------------------------------------

        matching_ids = name_to_ids.get(
            predecessor_name,
            []
        )

        if len(matching_ids) == 0:

            errors.append(
                f"Unable to find activity: "
                f"{predecessor_name}"
            )

            continue

        if len(matching_ids) > 1:

            errors.append(
                f"Duplicate activity name detected: "
                f"{predecessor_name}"
            )

            continue

        updated.at[
            index,
            "Predecessor"
        ] = matching_ids[0]

        updated.at[
            index,
            "Relationship"
        ] = relationship

    return updated, errors

# ==========================================================
# RELATIONSHIP VALIDATION
# ==========================================================

def validate_relationships(activities, reviewed_data=None):
    """
    Validate activity relationships before schedule calculation.

    Checks:
    1. All predecessors exist.
    2. No activity is its own predecessor.
    3. Relationship type is valid.
    4. No-predecessor activities have no predecessor.
    5. Relationships requiring a predecessor have one.
    6. No circular dependencies.
    7. No unresolved AI review items remain.
    """

    errors = []

    if activities is None or activities.empty:
        errors.append(
            "No activities are available for validation."
        )
        return False, errors

    # ------------------------------------------------------
    # Check AI review status
    # ------------------------------------------------------

    if reviewed_data is not None and not reviewed_data.empty:

        if "Status" in reviewed_data.columns:

            pending_rows = reviewed_data[
                reviewed_data["Status"].astype(str).str.strip()
                == "⏳ Pending"
            ]

            if not pending_rows.empty:

                for _, row in pending_rows.iterrows():

                    errors.append(
                        f"{row['ID']}: Relationship review "
                        "is still pending."
                    )

    # ------------------------------------------------------
    # Build Activity ID lookup
    # ------------------------------------------------------

    activity_ids = set()

    for _, row in activities.iterrows():

        activity_id = str(
            row["ID"]
        ).strip()

        if activity_id:
            activity_ids.add(activity_id)

    # ------------------------------------------------------
    # Validate each relationship
    # ------------------------------------------------------

    graph = {}

    for _, row in activities.iterrows():

        activity_id = str(
            row["ID"]
        ).strip()

        predecessor = str(
            row["Predecessor"]
        ).strip()

        relationship = str(
            row["Relationship"]
        ).strip()

        graph[activity_id] = predecessor

        # ----------------------------------------------
        # Relationship type
        # ----------------------------------------------

        if relationship not in RELATIONSHIP_OPTIONS:

            errors.append(
                f"{activity_id}: Invalid relationship "
                f"'{relationship}'."
            )

        # ----------------------------------------------
        # No predecessor
        # ----------------------------------------------

        if relationship == "No Predecessor":

            if predecessor and predecessor.lower() not in [
                "none",
                "none 🔍"
            ]:

                errors.append(
                    f"{activity_id}: Relationship is "
                    "'No Predecessor' but a predecessor "
                    f"'{predecessor}' is assigned."
                )

            continue

        # ----------------------------------------------
        # Relationship requires predecessor
        # ----------------------------------------------

        if not predecessor or predecessor.lower() in [
            "none",
            "none 🔍"
        ]:

            errors.append(
                f"{activity_id}: Relationship "
                f"'{relationship}' requires a predecessor."
            )

            continue

        # ----------------------------------------------
        # Self predecessor
        # ----------------------------------------------

        if predecessor == activity_id:

            errors.append(
                f"{activity_id}: Activity cannot be "
                "its own predecessor."
            )

            continue

        # ----------------------------------------------
        # Predecessor exists
        # ----------------------------------------------

        if predecessor not in activity_ids:

            errors.append(
                f"{activity_id}: Predecessor "
                f"'{predecessor}' does not exist."
            )

    # ------------------------------------------------------
    # Detect circular dependencies
    # ------------------------------------------------------

    visited = set()
    active_path = set()

    def visit(activity_id, path):

        if activity_id in active_path:

            cycle_start = path.index(activity_id)

            cycle = (
                path[cycle_start:]
                + [activity_id]
            )

            errors.append(
                "Circular dependency detected: "
                + " → ".join(cycle)
            )

            return

        if activity_id in visited:
            return

        visited.add(activity_id)
        active_path.add(activity_id)

        predecessor = graph.get(activity_id)

        if (
            predecessor
            and predecessor in graph
        ):

            visit(
                predecessor,
                path + [predecessor]
            )

        active_path.remove(activity_id)

    for activity_id in graph:

        if activity_id not in visited:

            visit(
                activity_id,
                [activity_id]
            )

    # ------------------------------------------------------
    # Remove duplicate error messages
    # ------------------------------------------------------

    errors = list(dict.fromkeys(errors))

    if errors:
        return False, errors

    return True, []

# ==========================================================
# AI RELATIONSHIP ANALYSIS UI
# ==========================================================

def render_ai_relationship_analysis(activities):

    st.subheader("AI Schedule Builder")

    st.caption(
        "AI analyzes the construction activities and proposes "
        "predecessors and relationships. Review or modify the "
        "AI proposal before saving."
    )

    if activities.empty:

        st.info(
            "No activities are available for AI analysis."
        )

        return

    # ======================================================
    # RUN AI ANALYSIS
    # ======================================================

    # ======================================================
    # AI CONNECTION
    # ======================================================

    api_key = st.text_input(
        "Groq API Key",
        type="password",
        placeholder="Enter Groq API key",
        key="step3_ai_schedule_api_key",
        help=(
            "Your API key is used only for the current "
            "AI scheduling session."
        ),
    )

    model_options = {
        "gpt-oss-20b": "openai/gpt-oss-20b",
        "gpt-oss-120b": "openai/gpt-oss-120b",
    }

    selected_model_name = st.selectbox(
        "AI Model",
        list(model_options.keys()),
        key="step3_ai_schedule_model",
    )

    selected_model = model_options[
        selected_model_name
    ]


    # ======================================================
    # RUN AI SCHEDULE BUILDER
    # ======================================================

    if st.button(
        "🤖 Generate AI Schedule Logic",
        type="primary",
        use_container_width=True
    ):

        if not api_key.strip():

            st.error(
                "Please enter your Groq API key first."
            )

        else:

            with st.spinner(
                "AI is analyzing the construction sequence..."
            ):

                try:

                    suggestions = (
                        get_ai_schedule_suggestions(
                            activities,
                            api_key.strip(),
                            selected_model,
                        )
                    )

                    st.session_state.ai_suggestions = (
                        suggestions.copy()
                    )

                    st.session_state.ai_original_suggestions = (
                        suggestions.copy()
                    )

                    st.session_state.ai_editor_data = (
                        suggestions.copy()
                    )

                    st.session_state.ai_editor_version = 0

                    st.session_state.ai_relationship_saved = (
                        False
                    )

                    st.session_state.ai_validation_passed = (
                        False
                    )

                    st.session_state.ai_saved_relationships = (
                        None
                    )

                    st.session_state.pop(
                        "ai_saved_review",
                        None
                    )

                    st.session_state.pop(
                        "proposed_schedule",
                        None
                    )

                    st.session_state.pop(
                        "schedule_warnings",
                        None
                    )

                    st.success(
                        "AI schedule logic generated successfully."
                    )

                    st.rerun()

                except Exception as exc:

                    st.error(
                        "AI schedule generation failed."
                    )

                    st.exception(exc)


    # ======================================================
    # NO ANALYSIS YET
    # ======================================================

    if "ai_editor_data" not in st.session_state:

        st.info(
            "Click **AI Analysis** to generate "
            "relationship suggestions."
        )

        return

    # ======================================================
    # ENSURE VERSION EXISTS
    # ======================================================

    if "ai_editor_version" not in st.session_state:

        st.session_state.ai_editor_version = 0

    # ======================================================
    # AI ANALYSIS TABLE
    # ======================================================

    st.write("### AI Relationship Analysis")

    st.caption(
        "Review the AI proposal for each activity. "
        "Tick **Approve** if the proposal is correct. "
        "If you change the predecessor or relationship, "
        "the status automatically becomes ✏️ Modified."
    )

    suggestions = (
        st.session_state.ai_editor_data.copy()
    )

    # ------------------------------------------------------
    # ADD WBS INFORMATION FOR AI REVIEW
    # ------------------------------------------------------

    ai_display_data = suggestions.copy()

    approved_wbs = st.session_state.get(
        "wbs",
        pd.DataFrame()
    )

    if (
        isinstance(approved_wbs, pd.DataFrame)
        and not approved_wbs.empty
        and "WBS ID" in approved_wbs.columns
        and "WBS Name" in approved_wbs.columns
    ):

        wbs_name_lookup = (
            approved_wbs[
                [
                    "WBS ID",
                    "WBS Name"
                ]
            ]
            .drop_duplicates(
                subset=["WBS ID"]
            )
            .set_index("WBS ID")["WBS Name"]
            .to_dict()
        )

        # Match each activity to its authoritative WBS.
        activity_wbs_lookup = {}

        for _, activity_row in activities.iterrows():

            activity_id = str(
                activity_row["ID"]
            ).strip()

            activity_wbs_lookup[activity_id] = (
                str(
                    activity_row.get("WBS", "")
                ).strip()
            )

        ai_display_data["WBS ID"] = (
            ai_display_data["ID"]
            .astype(str)
            .str.strip()
            .map(activity_wbs_lookup)
            .fillna("")
        )

        ai_display_data["WBS Name"] = (
            ai_display_data["WBS ID"]
            .map(wbs_name_lookup)
            .fillna("")
        )

    else:

        ai_display_data["WBS ID"] = ""
        ai_display_data["WBS Name"] = ""

    editable_columns = [
        "ID",
        "WBS ID",
        "WBS Name",
        "Activity",
        "Suggested Predecessor",
        "Relationship",
        "Confidence",
        "Reason",
        "Approve",
        "Status"
    ]

    widget_key = (
        "ai_relationship_editor_widget_"
        + str(
            st.session_state.ai_editor_version
        )
    )

    st.data_editor(

        ai_display_data[editable_columns],

        use_container_width=True,

        hide_index=True,

        disabled=[
            "WBS ID",
            "WBS Name",
            "ID",
            "Activity",
            "Confidence",
            "Reason",
            "Status"
        ],

        column_config={

            "ID":
                st.column_config.TextColumn(
                    "ID"
                ),

            "WBS ID":
                st.column_config.TextColumn(
                    "WBS ID"
                ),

            "WBS Name":
                st.column_config.TextColumn(
                    "WBS Name"
                ),

            "Activity":
                st.column_config.TextColumn(
                    "Activity"
                ),

            "Suggested Predecessor":
                st.column_config.SelectboxColumn(
                    "Predecessor",
                    options=[
                        "None 🔍"
                    ]
                    +
                    [
                        str(name).strip()
                        for name
                        in activities["Activity"]
                    ],
                    help=(
                        "Select the predecessor "
                        "activity."
                    )
                ),

            "Relationship":
                st.column_config.SelectboxColumn(
                    "Relationship",
                    options=RELATIONSHIP_OPTIONS
                ),

            "Confidence":
                st.column_config.TextColumn(
                    "Confidence"
                ),

            "Reason":
                st.column_config.TextColumn(
                    "AI Reason"
                ),

            "Approve":
                st.column_config.CheckboxColumn(
                    "Approve",
                    help=(
                        "Approve this AI proposal "
                        "without changing it."
                    ),
                    default=False
                ),

            "Status":
                st.column_config.TextColumn(
                    "Status"
                )
        },

        key=widget_key,

        on_change=process_ai_editor_change
    )

    # ======================================================
    # SAVE CHANGES
    # ======================================================

    st.divider()

    st.write("### Review Status")

    current_data = (
        st.session_state.ai_editor_data.copy()
    )

    pending_count = int(
        (
            current_data["Status"]
            == "⏳ Pending"
        ).sum()
    )

    approved_count = int(
        (
            current_data["Status"]
            == "✅ Approved"
        ).sum()
    )

    modified_count = int(
        (
            current_data["Status"]
            == "✏️ Modified"
        ).sum()
    )

    existing_count = int(
        (
            current_data["Status"]
            == "📌 Existing"
        ).sum()
    )

    col1, col2, col3, col4 = st.columns(4)

    with col1:

        st.metric(
            "Pending",
            pending_count
        )

    with col2:

        st.metric(
            "Approved",
            approved_count
        )

    with col3:

        st.metric(
            "Modified",
            modified_count
        )

    with col4:

        st.metric(
            "Existing",
            existing_count
        )

    if pending_count > 0:

        st.warning(
            f"{pending_count} relationship(s) still "
            "require review."
        )

    elif modified_count > 0:

        st.info(
            "All relationships have been reviewed, "
            "but modified relationships should be "
            "checked before final validation."
        )

    else:

        st.success(
            "All relationships have been reviewed."
        )

    # ======================================================
    # SAVE CHANGES
    # ======================================================

    st.divider()

    st.write("### Review Status")

    current_data = (
        st.session_state.ai_editor_data.copy()
    )

    pending_count = int(
        (
            current_data["Status"]
            == "⏳ Pending"
        ).sum()
    )

    approved_count = int(
        (
            current_data["Status"]
            == "✅ Approved"
        ).sum()
    )

    modified_count = int(
        (
            current_data["Status"]
            == "✏️ Modified"
        ).sum()
    )

    existing_count = int(
        (
            current_data["Status"]
            == "📌 Existing"
        ).sum()
    )

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.metric(
            "Pending",
            pending_count
        )

    with col2:
        st.metric(
            "Approved",
            approved_count
        )

    with col3:
        st.metric(
            "Modified",
            modified_count
        )

    with col4:
        st.metric(
            "Existing",
            existing_count
        )

    if pending_count > 0:

        st.warning(
            f"{pending_count} relationship(s) still "
            "require review."
        )

    elif modified_count > 0:

        st.info(
            "Modified relationships have been reviewed. "
            "They will be checked again during final "
            "relationship validation."
        )

    else:

        st.success(
            "All relationships have been reviewed."
        )

    # ======================================================
    # SAVE BUTTON
    # ======================================================

    if st.button(
        "💾 Save Changes",
        type="primary",
        use_container_width=True
    ):

        latest_data = (
            st.session_state.ai_editor_data.copy()
        )

        pending_count = int(
            (
                latest_data["Status"]
                == "⏳ Pending"
            ).sum()
        )

        if pending_count > 0:

            st.error(
                f"Cannot save yet. "
                f"{pending_count} relationship(s) "
                "are still pending."
            )

        else:

            reviewed_activities, errors = (
                convert_ai_relationships_to_activity_data(
                    activities,
                    latest_data
                )
            )

            if errors:

                for error in errors:
                    st.error(error)

            else:

                st.session_state.ai_saved_relationships = (
                    reviewed_activities.copy()
                )

                st.session_state.ai_saved_review = (
                    latest_data.copy()
                )

                st.session_state.ai_relationship_saved = (
                    True
                )

                st.success(
                    "AI-reviewed relationship changes "
                    "saved successfully."
                )

                st.rerun()

    # ======================================================
    # SAVED STATUS
    # ======================================================

    if st.session_state.get(
        "ai_relationship_saved",
        False
    ):

        st.success(
            "AI relationship review is saved and ready "
            "for final validation."
        )

        st.caption(
            "You can still modify the AI table above. "
            "If you make further changes, click "
            "**Save Changes** again."
        )

    # ======================================================
    # RELATIONSHIP VALIDATION
    # ======================================================

    st.divider()

    st.write("### Relationship Validation")

    st.caption(
        "Validate the saved AI-reviewed relationships "
        "before calculating the project schedule."
    )

    if not st.session_state.get(
        "ai_relationship_saved",
        False
    ):

        st.info(
            "Save the AI relationship review first. "
            "Validation will then become available."
        )

    else:

        if st.button(
            "🔍 Validate Relationships",
            use_container_width=True
        ):

            saved_relationships = (
                st.session_state.get(
                    "ai_saved_relationships"
                )
            )

            saved_review = (
                st.session_state.get(
                    "ai_saved_review"
                )
            )

            if saved_relationships is None:

                st.error(
                    "No saved relationship data is available."
                )

                st.session_state.ai_validation_passed = False

            else:

                validation_passed, validation_errors = (
                    validate_relationships(
                        saved_relationships,
                        saved_review
                    )
                )

                if validation_passed:

                    st.session_state.ai_validation_passed = True

                    st.success(
                        "✅ Relationship validation passed. "
                        "All reviewed relationships are valid "
                        "and no circular dependencies were found."
                    )

                else:

                    st.session_state.ai_validation_passed = False

                    st.error(
                        "❌ Relationship validation failed. "
                        "Please correct the following issues:"
                    )

                    for error in validation_errors:

                        st.error(
                            f"• {error}"
                        )
